# Workflow
# Workflow should have a name.
# No indentation is required for mapping the workflow.
name: Hello

# 'on' tells GitHub when the workflow should run.
on:
  workflow_dispatch:

# Jobs
# A workflow contains one or more jobs.
# 'jobs' defines what the workflow should do.
jobs:
  # First job
  say-hello:
    runs-on: ubuntu-latest

    # Steps
    # Steps are executed sequentially within a job.
    steps:
      # Action
      - name: Say hello to everyone
        run: echo "Hello Mitra"
