# GOAL:
# Whenever someone changes a Python file,
# the linter checks the code for syntax, formatting, and style issues.

name: Auto Linter

on:
  push:
    paths:
      - "**/*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    # These steps automatically clone the repository
    # into the GitHub Actions runner.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ruff Linter
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check .
