#GOAL: whenever someone changes the Python code,
# the linter will check if the syntax, format, and indentation (Linter) are correct or not

name: Auto Linter

on:
  push:
    paths:
      - "*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    # These steps automatically clone the current branch into the runner.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Linter
        run: pip install ruff
